<a href="https://colab.research.google.com/github/nivla0607/CS114.L22.KHCL/blob/main/ThaoTacVoiDuLieu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install mxnet==1.6.0

In [ ]:
from mxnet import np, npx
npx.set_np()

In [ ]:
x = np.arange(12)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
x.shape

(12,)

In [ ]:
x.size

12

In [ ]:
x = x.reshape(3,4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
x.reshape(3,-1)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
np.empty((3, 4))

array([[1.5746807e+11, 3.0616970e-41, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00]])

In [ ]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
arr = np.random.normal(0, 1, size=(4, 4))
arr, arr.sum()

(array([[ 1.0731696 ,  1.8307649 ,  0.12017461, -1.1468065 ],
        [-0.9711102 ,  0.05383795, -0.77569664, -2.5074806 ],
        [-0.7882176 , -0.59164983,  0.7417728 ,  0.8586049 ],
        [-1.4734439 , -0.22794184, -1.0730928 ,  0.20131476]]),
 array(-4.6758003))

In [ ]:
np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]])

In [ ]:
x = np.array([7, 11, 4, 13])
y = np.array([2,9, 11, 4])
x + y, x - y, x * y, x / y, x ** y  

(array([ 9., 20., 15., 17.]),
 array([ 5.,  2., -7.,  9.]),
 array([14., 99., 44., 52.]),
 array([3.5       , 1.2222222 , 0.36363637, 3.25      ]),
 array([4.9000000e+01, 2.3579476e+09, 4.1943040e+06, 2.8561000e+04]))

In [ ]:
np.exp(x)

array([1.0966332e+03, 5.9874141e+04, 5.4598148e+01, 4.4241341e+05])

In [ ]:
x = np.arange(12).reshape(3, 4)
y = np.array([[5, 7, 3, 8], [1, 9, 4, 4], [5, 9, 7, 9]])
np.concatenate([x, y], axis=0), np.concatenate([x, y], axis=1)

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 5.,  7.,  3.,  8.],
        [ 1.,  9.,  4.,  4.],
        [ 5.,  9.,  7.,  9.]]),
 array([[ 0.,  1.,  2.,  3.,  5.,  7.,  3.,  8.],
        [ 4.,  5.,  6.,  7.,  1.,  9.,  4.,  4.],
        [ 8.,  9., 10., 11.,  5.,  9.,  7.,  9.]]))

In [ ]:
x == y

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False]])

In [ ]:
x = np.arange(16).reshape(4, 4)
x,x[-1],x[0:3] 

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]),
 array([12., 13., 14., 15.]),
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]))

In [ ]:
x[0,3] = 9
x[1,2] = 6
x[2,0] = 1
x[3,1] = 2
x


array([[ 0.,  1.,  2.,  9.],
       [ 4.,  5.,  6.,  7.],
       [ 1.,  9., 10., 11.],
       [12.,  2., 14., 15.]])

In [ ]:
x[0:3, :] = 6
x 

array([[ 6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  6.],
       [12.,  2., 14., 15.]])

In [ ]:
y = np.arange(16).reshape(4,4)
y

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [ ]:
before = id(y)
y = y + x
before == id(y)

False

In [ ]:
z = np.zeros_like(y)
print(id(z))
z[:] = x + y
print(id(z)) 

140005275363440
140005275363440


In [ ]:
before1 = id(x)
x -= y
before1 == id(x)

True

In [ ]:
a = np.array([3.5,4.5,5.9,6.7])
a,a[0].item(),float(a[1]),int(a[2])

(array([3.5, 4.5, 5.9, 6.7]), 3.5, 4.5, 5)

In [ ]:
a = np.array([3.5])
a, a.item(), float(a), int(a)

(array([3.5]), 3.5, 3.5, 3)

In [ ]:
a = np.array([5,6,7]).reshape(3,1)
b = np.array([3,4])
print(a)
print(b)


[[5.]
 [6.]
 [7.]]
[3. 4.]


In [ ]:
a = np.array([[5,5],[6,6],[7,7]])
b = np.array([[3,4],[3,4],[3,4]])
print(a)
print(b)

[[5. 5.]
 [6. 6.]
 [7. 7.]]
[[3. 4.]
 [3. 4.]
 [3. 4.]]


In [ ]:
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a**b) 

In [ ]:
array1 = x.asnumpy()
array2 = np.array(array1)
type(array1),type(array2)

(numpy.ndarray, mxnet.numpy.ndarray)

In [ ]:
test = np.array([3.5])
test.item(),float(test),int(test)

(3.5, 3.5, 3)

In [ ]:
test1 = np.arange(12).reshape(2,2,3)
print(test1)
test1[1][0][1].item()

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


7.0